version: '3.7'
services:

  task-service:
    image: lapierre/task-service-core:${TASK_SERVICE_CORE}
    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Warsaw
      - SPRING_PROFILES_ACTIVE=docker,pg
    ports:
      - "8080:8080"

  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=task
    ports:
      - "5432:5432"

volumes:
  pg_data:
