create table proces_definition
(
    key                varchar(255) not null,
    behalf_created_by  varchar(255),
    behalf_modified_by varchar(255),
    created            timestamp,
    created_by         varchar(255),
    last_modified      timestamp,
    modified_by        varchar(255),
    version            int4         not null,
    form_schema        jsonb,
    name               varchar(255),
    renewal            boolean      not null,
    primary key (key)
);

create table process_steps_definition
(
    step_key               varchar(255) not null,
    behalf_created_by      varchar(255),
    behalf_modified_by     varchar(255),
    created                timestamp,
    created_by             varchar(255),
    last_modified          timestamp,
    modified_by            varchar(255),
    version                int4         not null,
    form_schema            jsonb,
    lp                     int4         not null,
    step_name              varchar(255),
    process_definition_key varchar(255) not null,
    primary key (process_definition_key, step_key)
);

create table running_process
(
    id                     int8 generated by default as identity,
    behalf_created_by      varchar(255),
    behalf_modified_by     varchar(255),
    created                timestamp,
    created_by             varchar(255),
    last_modified          timestamp,
    modified_by            varchar(255),
    version                int4         not null,
    external_id            varchar(255),
    owner                  varchar(255),
    renewal                boolean      not null,
    status                 varchar(255),
    json_values            jsonb,
    process_definition_key varchar(255) not null,
    primary key (id)
);

create table running_process_task
(
    step_key           varchar(255) not null,
    behalf_created_by  varchar(255),
    behalf_modified_by varchar(255),
    created            timestamp,
    created_by         varchar(255),
    last_modified      timestamp,
    modified_by        varchar(255),
    version            int4         not null,
    execution_date     date,
    na                 boolean      not null,
    reminder_date      date,
    reminder_time      time,
    json_values        jsonb,
    process_id         int8         not null,
    primary key (process_id, step_key)
);

alter table if exists process_steps_definition
    add constraint FKkosn8wa11s72lw1c8es0ybh3a foreign key (process_definition_key) references proces_definition;

alter table if exists running_process
    add constraint FKk324dvq7hqr3yik2ou8j408xg foreign key (process_definition_key) references proces_definition;

alter table if exists running_process_task
    add constraint FK9j39ibpbj27vds2s787oxsrr foreign key (process_id) references running_process;
