spring:
    profiles:
        include: migratedb, metrisc
#eureka:
#    client:
#        service-url:
#            defaultZone: http://eureka:8761/eureka/

#security:
#    oauth2:
#        resource:
#            user-info-uri: http://auth:9001/api/user/logged

