#eureka:
#    client:
#        fetch-registry: true
#        register-with-eureka: true
#        healthcheck:
#            enabled: true
#        service-url:
#            defaultZone: http://localhost:8761/eureka/
#    instance:
#        prefer-ip-address: true

info:
    build:
        version: '@project.version@'
    java:
        version: '@java.version@'
logging:
    level:
        io.alapierre.task.service: DEBUG
        com:
            netflix: WARN
management:
    health:
        defaults:
            enabled: true
#security:
#    oauth2:
#        resource:
#            user-info-uri: http://localhost:9001/api/user/logged
server:
    port: 8080
spring:
    config:
        use-legacy-processing: true
    flyway:
        enabled: false
