spring:
    flyway:
        baseline-on-migrate: true
        enabled: true
        outOfOrder: true
        placeholder-prefix: $${
        placeholder-suffix: '}'
        schemas: tasks
        ignore-missing-migrations: true
